#!/bin/bash

# Dotfiles installation script
# Sets up Homebrew packages, symlinks, SSH, and git for a new machine

set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Installing dotfiles from $DOTFILES_DIR"
echo ""

# --- Homebrew bootstrap ---
if ! command -v brew >/dev/null 2>&1; then
  echo "Homebrew not found. Installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Put brew on PATH for this session + future login shells (Apple Silicon / Intel)
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
  BREW_SHELLENV_LINE='eval "$(/opt/homebrew/bin/brew shellenv)"'
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
  BREW_SHELLENV_LINE='eval "$(/usr/local/bin/brew shellenv)"'
fi

if [[ -n "${BREW_SHELLENV_LINE:-}" ]]; then
  if [[ ! -f "$HOME/.zprofile" ]] || ! grep -Fq 'brew shellenv' "$HOME/.zprofile" 2>/dev/null; then
    echo "$BREW_SHELLENV_LINE" >> "$HOME/.zprofile"
    echo "✓ Added brew to ~/.zprofile"
  fi
fi

# --- Packages (apps + CLI) via Brewfile ---
echo "Installing packages from Brewfile..."
# Trust third-party taps used by this Brewfile (Homebrew may refuse untrusted taps)
if command -v brew >/dev/null 2>&1; then
  brew tap android/tap 2>/dev/null || true
  brew tap nikitabobko/tap 2>/dev/null || true
  # Newer Homebrew may require explicit trust
  brew trust android/tap 2>/dev/null || true
  brew trust nikitabobko/tap 2>/dev/null || true
fi

brew bundle --file="$DOTFILES_DIR/Brewfile"
echo "✓ Brew packages installed"

# --- Android CLI post-setup ---
if command -v android >/dev/null 2>&1; then
  echo ""
  echo "Setting up Android CLI..."
  # Init agent skills / environment (safe to re-run)
  android init >/dev/null 2>&1 || true
  echo "✓ Android CLI ready (run 'android update' anytime)"
fi

# --- Grok CLI ---
echo ""
if command -v grok >/dev/null 2>&1; then
  echo "✓ Grok CLI already installed ($(grok --version 2>/dev/null || echo 'ok'))"
else
  echo "Installing Grok CLI..."
  curl -fsSL https://x.ai/cli/install.sh | bash
  echo "✓ Grok CLI installed"
fi

# Create symlink for .zshrc
if [ -f "$HOME/.zshrc" ] && [ ! -L "$HOME/.zshrc" ]; then
  echo "Backing up existing .zshrc to .zshrc.backup"
  mv "$HOME/.zshrc" "$HOME/.zshrc.backup"
fi

ln -sf "$DOTFILES_DIR/.zshrc" "$HOME/.zshrc"
echo "✓ Linked .zshrc"

# Create .zsh_secrets if it doesn't exist
if [ ! -f "$DOTFILES_DIR/.zsh_secrets" ]; then
  echo "Creating .zsh_secrets file..."
  cat > "$DOTFILES_DIR/.zsh_secrets" << 'EOF'
# --- API KEYS (keep private)
# This file contains sensitive information and should not be committed to git
export GEMINI_API_KEY=""
EOF
  echo "✓ Created .zsh_secrets (remember to add your API keys!)"
else
  echo "✓ .zsh_secrets already exists"
fi

# --- SSH Setup ---
echo ""
echo "Setting up SSH configuration..."

mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

# Private hosts file (never committed)
if [ ! -f "$DOTFILES_DIR/ssh/config.local" ]; then
  cp "$DOTFILES_DIR/ssh/config.local.example" "$DOTFILES_DIR/ssh/config.local"
  echo "✓ Created ssh/config.local from example (add private hosts here)"
else
  echo "✓ ssh/config.local already exists"
fi

# ~/.ssh/config must be a real file (not a symlink) so it can Include both
# the tracked public config and the gitignored local config.
if [ -L "$HOME/.ssh/config" ]; then
  rm "$HOME/.ssh/config"
  echo "✓ Removed old ~/.ssh/config symlink"
elif [ -f "$HOME/.ssh/config" ] && ! grep -Fq "Generated by dotfiles" "$HOME/.ssh/config" 2>/dev/null; then
  if [ ! -f "$HOME/.ssh/config.dotfiles-backup" ]; then
    cp "$HOME/.ssh/config" "$HOME/.ssh/config.dotfiles-backup"
    echo "✓ Backed up existing ~/.ssh/config to ~/.ssh/config.dotfiles-backup"
  fi
fi

cat > "$HOME/.ssh/config" << EOF
# Generated by dotfiles install.sh — do not edit here.
# Public hosts:  $DOTFILES_DIR/ssh/config
# Private hosts: $DOTFILES_DIR/ssh/config.local

Include $DOTFILES_DIR/ssh/config
Include $DOTFILES_DIR/ssh/config.local
EOF
chmod 600 "$HOME/.ssh/config"
echo "✓ Wrote ~/.ssh/config (includes public + local config)"

# Copy any local SSH keys from ssh/ into ~/.ssh (copy, not symlink)
for key in "$DOTFILES_DIR"/ssh/*; do
  name=$(basename "$key")
  case "$name" in
    config|config.local|config.local.example) continue ;;
  esac
  if [[ "$name" == *.pub ]]; then
    cp "$key" "$HOME/.ssh/$name"
    chmod 644 "$HOME/.ssh/$name"
    echo "✓ Installed $name public key"
  elif [ -f "$key" ]; then
    cp "$key" "$HOME/.ssh/$name"
    chmod 600 "$HOME/.ssh/$name"
    echo "✓ Installed $name private key"
  fi
done

# --- Git Config Setup ---
echo ""
echo "Setting up Git configuration..."

# Identity files (real name/emails) — create from examples if missing
for id in identity-personal identity-work; do
  if [ ! -f "$DOTFILES_DIR/git/$id" ]; then
    cp "$DOTFILES_DIR/git/$id.example" "$DOTFILES_DIR/git/$id"
    echo "⚠ Created git/$id from example — replace placeholders with real name/email"
  else
    echo "✓ git/$id exists"
  fi
done

if grep -q 'you@work.example\|you@personal.example\|Your Name' \
  "$DOTFILES_DIR/git/identity-work" "$DOTFILES_DIR/git/identity-personal" 2>/dev/null; then
  echo ""
  echo "⚠ Git identity still has placeholders. Edit:"
  echo "   $DOTFILES_DIR/git/identity-personal"
  echo "   $DOTFILES_DIR/git/identity-work"
fi

if [ -f "$HOME/.gitconfig" ] && [ ! -L "$HOME/.gitconfig" ]; then
  echo "Backing up existing .gitconfig to .gitconfig.backup"
  mv "$HOME/.gitconfig" "$HOME/.gitconfig.backup"
fi

ln -sf "$DOTFILES_DIR/git/.gitconfig" "$HOME/.gitconfig"
echo "✓ Linked .gitconfig"

# Identity includes use fixed home paths (relative includes break with symlinks)
ln -sf "$DOTFILES_DIR/git/identity-personal" "$HOME/.gitconfig-identity-personal"
ln -sf "$DOTFILES_DIR/git/identity-work" "$HOME/.gitconfig-identity-work"
echo "✓ Linked git identity files"

# Clean up old include symlinks if present
rm -f "$HOME/.gitconfig-personal" "$HOME/.gitconfig-work"

echo ""
echo "Installation complete!"
echo ""
echo "Next steps:"
echo "1. Restore private files from backup: ./restore.sh <backup-dir>"
echo "   (or fill them in manually:)"
echo "   - $DOTFILES_DIR/git/identity-personal + identity-work (real emails)"
echo "   - $DOTFILES_DIR/.zsh_secrets (API keys)"
echo "   - $DOTFILES_DIR/ssh/config.local (private hosts)"
echo "2. Run: source ~/.zshrc"
echo "3. Generate GitHub SSH keys (if needed):"
echo "   ssh-keygen -t ed25519 -C 'you@personal.example' -f ~/.ssh/github-personal"
echo "   ssh-keygen -t ed25519 -C 'you@work.example' -f ~/.ssh/github-work"
echo "4. Add public keys to each GitHub account"
echo "5. Test: ssh -T git@github.com && ssh -T git@github-work"
echo "6. Android: android info && android sdk list"
echo "7. Grok: grok --version"
echo ""
